{{- if (.Values.secret).enabled }}
{{- range $nameSuffix, $data := .Values.secret.files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helm-api.name" $ }}-{{ $nameSuffix }}
  namespace: {{ template "helm-api.namespace" $ }}
  labels:
  {{- include "helm-api.labels" $ | nindent 4 }}
{{- if $.Values.secret.additionalLabels }}
{{ toYaml $.Values.secret.additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.secret.annotations }}
  annotations:
{{ toYaml $.Values.secret.annotations | indent 4 }}
{{- end }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- with .encodedData }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}
{{- end }}
